### PR TITLE
Make SOCRATES available via github artifacts

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR zips up the build for SOCRATES and makes it available via Github artifacts.

The automated releases work like this:
- Tag a version on main branch
- Push version to repo
- The `softprops/action-gh-release` detects a tagged commit and makes a release (we should test this when this is merged)

The action will build the package anyway and make them available at the actions page: https://github.com/nichollsh/SOCRATES/actions/runs/10182560102
Only a tagged version gets released.

### TODO
- [x] Automated release
- [x] Only run on main branch / tagged release
- [x] Put version in release body

### CODE REVIEW

**Review by nichollsh — APPROVED** [review]
Excellent. Thanks Stef!

**Comment by stefsmeets** [comment]
Not too fast, I want to make sure that it works 😁

**Comment by stefsmeets** [comment]
Could you approve the workflow and/or give me write access so that I can test/debug it myself?

**Comment by nichollsh** [comment]
I have invited you to become a Collaborator on this repository, which I believe should provide the permissions.

**Comment by stefsmeets** [comment]
@nichollsh Let me know if you are happy with this. Once this is merged we should test the automated release by pushing a tag to main.

**Comment by nichollsh** [comment]
Makes sense - I am happy with this, although I suppose we can only find out if it works when a tag is created. 

The SOCRATES documentation is historically a simple PDF file, so there's no "official" place to document this. The only documentation I have added is in `spectraltools` as a text file. 

For now, we could make a text file in the .github folder to explain what the workflow is doing, and then discuss how to better handle SOCRATES documentation. I do think a more robust unofficial documentation for SOCRATES would be useful, which could come in the form of a GitHub pages wiki, which would be consistent with what AGNI does, and what I believe also with what mkdocs will do for the other repositories.

**Pull request merged**
